### PR TITLE
Added Javacript Cat Clock & Added Username to Username.txt

### PR DESCRIPTION
**Pull request by testerslol123**
- Project JS cat clock was added.
- Added my username to username.txt

### CODE REVIEW

**Comment by testerslol123** [comment]
@shubhamgoel90 I just create some pull request regarding js things.
Would you like to check it out ?
Also I don't find any hacktoberfest label in here.

Thanks

**Comment by testerslol123** [comment]
@shubhamgoel90 umm.. Thank you for merging the code.
But can I request this to be labelled as "hacktoberfest" and "hacktoberfest-accepted"?
It would truly helpful for me

**Comment by testerslol123** [comment]
@shubhamgoel90 thank you for accepting. But I saw in hacktoberfest, and you need to add label into your main repo there to be counted. Here is the quote from hacktoberfest rules:

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

One last thing, can you add label "hacktoberfest" in your repository, it would be helpful for me and others as it would counted

**Comment by shubhamgoel90** [comment]
@testerslol123 I have already added the hacktoberfest in the topic of the repository. But, now this repository is not eligible for the Hacktoberfest as it is not of a specific topic or tech. So, Digital Ocean has removed such kind of repositories from the hacktoberfest.

**Pull request merged**
